### PR TITLE
add error report in .knn() when # of neighbors < k

### PR DESCRIPTION
**Pull request by weiy6**
https://github.com/mhahsler/recommenderlab/issues/43#issue-734093255

.knn <- function(sim, k){...}
When any user for prediction has fewer neighbors than k, the knn is a list instead of a matrix. The added if block checks whether knn is a list and if it is a list, stop the code and return a message indicating the user who has the fewest neighbors. The first is returned when there are multiple such users.

### CODE REVIEW

**Comment by mhahsler** [comment]
Hi weyi6, 

thanks for submitting this fix. Please send me examples that reproduce the problem. I will add them to the test code and then think about the fix.

**Comment by weiy6** [comment]
Hi Michael,

An example is the issue 43 (https://github.com/mhahsler/recommenderlab/issues/43#issue-734093255).
Here is a zip of the code and the data [issue43.zip](https://github.com/mhahsler/recommenderlab/files/5696816/issue43.zip).

Another example, which uses built-in data only, can be 
```
set.seed(1234)
data(MovieLense)
e <- evaluationScheme(MovieLense, method="split", train = 0.7, given = 10)
r <- Recommender(getData(e, "train"), method = "UBCF", parameter = list(nn = 400))
recom <- predict(r, getData(e, "known"), type="ratings")
```

Before the fix, the output is
```
Error in neighbors[, x] : incorrect number of dimensions
```

After the fix, the output is
```
Error in .knn(sim, k) : 
  400-nearest neighbors are requested but user 752 has only 230 neighbors
```

**Comment by weiy6** [comment]
Hi Michael, 

I have listed which commits causes the behavior change reported in https://github.com/mhahsler/recommenderlab/issues/43 and https://github.com/mhahsler/recommenderlab/issues/42. I have also listed possible four options that I can think of to resolve those issues. I am currently choosing option C but I am happy to do option D if you are interested. Please feel free to let me know.

Thank you!
Sincerely,
weiy6

### History
In commit https://github.com/mhahsler/recommenderlab/commit/ad5bdcec48e1b105f3c19c3183ee099474ad14d0,

to remove self matches, `.knn` was changed

from
```
.knn <- function(sim, k) apply(sim, MARGIN=1, FUN=function(x) head(
   order(x, decreasing=TRUE, na.last=TRUE), k))
```
to
```
.knn <- function(sim, k) {
 knn <- apply(sim, MARGIN = 1, FUN = function(x)
   head(order(x, decreasing = TRUE, na.last = NA), k))
 ## Note: self matches have a sim of NA. na.last = NA removes self matches!

 ## Note: apply drops to a vector if k==1
 if(k==1) knn <- as.matrix(t(knn))

 knn
}
```
Setting `na.last=NA` removes the `NA` from the matrix. It may causes the returned vectors for different users have different lengths when any user's number of available neighbors is smaller than `k`. Then the result variable `knn`
will be a list of arrays in different lengths instead of a matrix.

### Possible fixes
* Option A. Not removing self-matches. It will make the code work but it violates the intention of the algorithm.
* Option B. Removing self-matches differently. We can remove self-matches only and leaving other NAs in the matrix. However, even by doing so, the returned vectors may still have different lengths when part of the users have self-matches and the others don't.
* Option C. Asking code users to use a smaller `k` in `.knn`. This is what the current fix is doing. It reports the error and notify the code users about which user has the smallest number of neighbors so that the code users can choose a reasonable `k` without breaking the code.
* Option D. Notifying the code users before or during the `similarity` calculation. The users can be notified earlier and choose a reasonable `k` before running the costly `similarity` calculation. Such fix may change multiple parts of the current code but is good for code users in the long term.

**Comment by mhahsler** [comment]
I have just pushed a fix. I have decided to simplify the code. .knn now always returns a list. Let me know if this works for you.

**Pull request closed without merging**
